# Generated by Django 3.0.7 on 2020-06-09 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20200609_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='userprofile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='App.UserProfile'),
        ),
    ]
